---
root: true

plugins:
  - jest
  - babel

env:
  node: true
  jest: true
  browser: true


extends:
  - "airbnb-base"
  - "plugin:jest/recommended"

parserOptions:
  ecmaVersion: 2020

rules:
  no-console: 0
  import/extensions: 0
  no-underscore-dangle: [0, { "allow": ["__filename", "__dirname"] }]